# These are supported funding model platforms

github: [ j3k0 ]
patreon: join/2219243
open_collective: # Replace with a single Open Collective username
ko_fi: jchoelt
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7A4826SH6RJSE&source=url
